version: '4'

services:

  # Single MySQL service for both Order and Inventory services
  mysql:
    image: mysql:8.3.0
    container_name: ecommerce-services-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_services_db  # Single database for both services
    ports:
      - "3306:3306"  # Expose MySQL on localhost:3306
    volumes:
      - ./mysql:/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql  # Persist data for MySQL

  # MongoDB service for Product Service (if needed)
  mongodb:
    image: mongo:7.0.5
    container_name: ecommerce-services-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product_service
    ports:
      - "27017:27017"  # Exposing MongoDB on localhost:27017
    volumes:
      - ./data:/data/db  # Persist data in ./data folder

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql

