version: '3.8'

services:

  mysql:
    image: mysql:8.3.0
    container_name: ecommerce-services-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce_services_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:7.0.5
    container_name: ecommerce-services-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product_service
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - default
      - infra_default

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - default
      - infra_default

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    networks:
      - default
      - infra_default

volumes:
  mysql-data:
  mongo-data:

networks:
  default:
  infra_default:
    external: true
